# ==========================================================
# 2D Halton Points
# ==========================================================
#
# This file contains the 2D sampling code used for the function
# approximation experiments.
#
# Training points were generated by a Halton sequence with bases 2 and 3.
# The points are first generated in [0,1]^2 and then mapped to the
# physical domain [a,b]^2.
#
# The seed_offset does not randomize the points. It shifts the starting
# index of the Halton sequence:
#
#     start = 1 + seed_offset * N
#
# Therefore, seed_offset = 0 reproduces the first N Halton points, while
# different seed_offset values use different non-overlapping parts of
# the same Halton sequence.
# ==========================================================

import torch


# ==========================================================
# One-dimensional Halton sequence
# ==========================================================

def _halton_1d(n, base, device, start_index=1):
    """
    Generate a one-dimensional Halton sequence.

    Parameters
    ----------
    n : int
        Number of points.

    base : int
        Halton base. For the 2D experiments, we use base 2 and base 3.

    device : str
        Torch device, for example "cpu" or "cuda".

    start_index : int
        Starting index of the Halton sequence.

    Returns
    -------
    seq : torch.Tensor, shape (n,)
        Halton points in [0,1].
    """

    dtype = torch.get_default_dtype()

    seq = torch.zeros(n, device=device, dtype=dtype)
    f = 1.0

    i = torch.arange(
        start_index,
        start_index + n,
        device=device,
        dtype=dtype,
    )

    while torch.any(i > 0):
        f = f / base
        seq += f * (i % base)
        i = torch.floor(i / base)

    return seq


# ==========================================================
# Two-dimensional Halton points
# ==========================================================

def sample_halton_2d(N, domain, device, seed_offset=0):
    """
    Generate 2D Halton points in [a,b]^2.

    Parameters
    ----------
    N : int
        Number of points.

    domain : tuple
        Physical domain (a,b). The same interval is used for both
        coordinates.

    device : str
        Torch device.

    seed_offset : int
        Shift in the Halton sequence. This is used to generate different
        deterministic datasets.

    Returns
    -------
    pts : torch.Tensor, shape (N,2)
        Halton points in the physical domain [a,b]^2.
    """

    a, b = domain

    start = 1 + seed_offset * N

    x = _halton_1d(
        N,
        base=2,
        device=device,
        start_index=start,
    )

    y = _halton_1d(
        N,
        base=3,
        device=device,
        start_index=start,
    )

    pts = torch.stack([x, y], dim=1)

    return a + (b - a) * pts


# ==========================================================
# Optional mesh grid for evaluation
# ==========================================================

def sample_meshgrid_2d(g, domain, device):
    """
    Generate a uniform 2D mesh grid in [a,b]^2.

    This was used for evaluation/plotting, not for Halton training points.
    """

    a, b = domain

    x = torch.linspace(a, b, g, device=device)
    X, Y = torch.meshgrid(x, x, indexing="ij")

    pts = torch.stack(
        [X.reshape(-1), Y.reshape(-1)],
        dim=1,
    )

    return X, Y, pts


# ==========================================================
# Dispatcher
# ==========================================================

def sample_points_2d(N, domain, method, device, seed_offset=0):
    """
    Unified 2D sampler.

    method = "halton" gives N Halton training points.
    method = "mesh" gives an N by N evaluation grid.
    """

    if method == "halton":
        return sample_halton_2d(
            N=N,
            domain=domain,
            device=device,
            seed_offset=seed_offset,
        )

    if method == "mesh":
        return sample_meshgrid_2d(
            g=N,
            domain=domain,
            device=device,
        )

    raise ValueError(f"Unknown sampling method: {method}")